apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  root-username: admin
  root-password: admin123
  mongodb-uri: "mongodb://admin:admin123@mongo:27017/?authSource=admin"