apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  labels:
    app: mongo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exporter
  template:
    metadata:
      labels:
        app: mongo-exporter
    spec:
      containers:
        - name: mongo-exporter
          image: willianmarioti/mongo_exporter:v1
          ports:
            - containerPort: 9216
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongodb-uri
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"