apiVersion: v1
kind: Service
metadata:
  name: mongo-exporter
  labels:
    app: mongo-exporter
spec:
  selector:
    app: mongo-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216
  type: ClusterIP